flowchart LR
   markdown["`Custom tourism`"]
    newLines1["`Profile interests`"]
    newLines2["`Suggest package by location`"]
    newLines3["`Define 
Virgil of the experience`"]
    newLines4["`Virgil
briefs
meeting point staff`"]
    newLines5["`Schedule
meeting points`"]
    newLines6["`Adjust schedule`"]
    newLines7["`Collect
point-to-point
feed-back`"]
    newLines8["`Debrief 
network participants`"]
    newLines9["`Thesaurize 
feed-back`"]
    markdown --> newLines1
    markdown --> newLines2
    markdown --> newLines3
    markdown --> newLines4
    markdown --> newLines5
    markdown --> newLines6
    markdown --> newLines7
    markdown --> newLines8
    markdown --> newLines9